version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      - "2345:2345"
    tty: true
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE